name = "sierrabravo"
main = "src/index.js"
compatibility_date = "2023-11-21"

[vars]

[[ai]]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "users"
database_id = "6f25c49a-2469-4dde-9ff7-5c1d29931e46"